### ISSUE TITLE
Aucune conversion d'image

### ISSUE THREAD

**Issue by ZerooCool** [conseilgouz/plg_system_cgwebp_j4#1]
Bonjour,
Je n'ai aucun message d'erreur dans les logs.
Le bouton debug ne m'apporte aucune information.

J'ai testé les dossiers :
media/plg_system_cgwebp/_cache
media/plg_system_cgwebp/
images/
images/webp/

Ainsi que les deux options, utiliser MEDIA, ou, utiliser le même dossier.

J'ai testé le bouton de vérification webp sur le serveur, c'est validé comme étant OK.

Le site : https://joomla.amis-sh.fr

**Comment by conseilgouz** [comment]
Bonjour,
Votre site n'est pas accessible.
Pour effectuer la conversion, ce plugin utilise GD. Est-il actif sur votre site ?
Au niveau du paramétrage du plugin, il y a la bouton "Check WEBP Support" qui permet de vérifier que le prérequis est ok:
![webp](https://github.com/conseilgouz/plg_system_cgwebp_j4/assets/19435246/76e699b2-f271-4cc6-9457-7b8863f795e6)

Pascal

**Comment by conseilgouz** [comment]
No answer, closing

**Comment by ZerooCool** [comment]
Bonjour,

GD est activé.
Check WEBP Support dit OK.
Aucun message d'erreur dans les logs.
Aucune erreur dans la console web.

J'utilise le templates fedaro_free qui utilise Helix Ultimate Framework. <--

Le plugin ne semble pas travailler, le tableau php activé par le mode debug, en bas de page, reste vide de données, seule la structure du tableau est affichée.

Les images affichées sur le site sont toujours en png.

**Comment by conseilgouz** [comment]
Le plugin cherche les images du type sélectionné (jpg et/ou png) dans le répertoire images par défaut.

Pouvez-vous mettre une copie écran de votre paramétrage du plugin webp ?

D'autre part, votre site n'est pas accessible.

Pascal

**Comment by conseilgouz** [comment]
Bonjour,
Je viens de faire des essais complémentaires avec votre template (Fedaro) en Joomla 5.1.2 où j'ai dû modifier quelques surcharges pour passer.
Je ne suis pas parvenu à recréer votre problème.
Quelle version Joomla utilisez vous ?
Avez-vous des plugins spécifiques en plus de ceux de votre template?
Avez-vous du code spécifique sur ce template ?
Pascal

**Comment by ZerooCool** [comment]
Bonjour,
" J'ai dû modifier quelques surcharges pour passer. " ?
C'est à dire ?

Voilà la capture d'écran de la configuration actuelle :
![cgwebp](https://github.com/user-attachments/assets/7eb22786-99e2-4779-8db9-e0fdede96a01)

Voilà le report du debug en bas de toutes les pages ( Le tableau semble vide ) : 
Array
(
    [media/plg_system_cgwebp/_cache] => Array
        (
        )

)

Le site est en ligne, vous pouvez confirmer si il est accessible ?
https://joomla.amis-sh.fr

Les CSP actuellement configurées ralentissent l'affichage, mais, cela devrait fonctionner.
Je n'ai pas d'erreurs critiques dans la console du navigateur.

**Comment by conseilgouz** [comment]
Bonjour,

Le répertoire est incorrect : il s'agit du répertoire d'origine des images, donc, mettre images devrait fonctionner.

Au niveau des surcharges, avec le template fedaro_free en Joomla 5.1.2, j'ai eu des erreurs sur templates\fedaro_free\html\com_content\article\default.php à cause de RouteHelper non défini, ainsi que templates\fedaro_free\html\layouts\joomla\content\blog_style_default_related_item_title.php

Note : je vais ajouter une description sur la zone répertoire afin de lever l'ambiguïté.

Pascal

**Comment by ZerooCool** [comment]
Merci de votre réponse.
Si je renseigne le répertoire : <strike>media/plg_system_cgwebp/_cache ( Recommandé dans la description )</strike> au lieu du répertoire images/
J'ai l'erreur Undefined array key "HTTP_ACCEPT" in /plugins/system/cgwebp/src/Helper/CgwebpHelper.php on line 42'

J'aurais aimé utiliser ce choix de répertoire (media/plg_system_cgwebp/_cache) pour garder la main sur les images générées et pouvoir éventuellement les supprimer, si je devais désactiver le plugin.
Est-ce possible ?
OUI !
Il faut utiliser le  **bouton Media** OU Même. J'utilise bien le bouton Media, donc, le **chemin de stockage vers media/plg_system_cgwebp/_cache/...** pour les images qui se trouvent dans **le répertoire images/ qui doit être renseigné** comme chemin pour localiser les images à transformer.

Je confirme le bon fonctionnement du plugin avec la saisie du répertoire " images/ "
Je n'ai pas vu d'erreurs dans les logs avec ce choix de répertoire.
Je n'ai pas vu d'erreurs dans les logs concernant des surcharges.
Je n'ai rien fais dans ce sens, me faut t'il faire quelque chose ?
Super travail ce plugin !
Merci.

**Comment by ZerooCool** [comment]
C'est parfait, c'est bien le répertoire "media/plg_system_cgwebp/_cache/..." qui contient les images converties.
Le tableau php retourne correctement les éléments modifiés.

<strike>NB : Je remarque que le plugin va convertir une image déjà en .webp.
En fait non.</strike>
C'est l'image glider-large.png qui est convertie deux fois ?
Elle se retrouve en élément 0 et 1 du tableau, avec le même hash : e48d04766b597c64f756a8ef529e7716

Je remarque que j'ai deux appels à cette image glider-large.png, peut-être pour un mode responsive.
Il doit sagir du comportement par défaut du template.
La même image est donc traitée ? / affichée deux fois dans le tableau php.

```
`Array
(
    [images/] => Array
        (
            [0] => Array
                (
                    [source] => images/structure/glider-large.png
                    [target] => media/plg_system_cgwebp/_cache/images/structure/glider-large.webp?ver=e48d04766b597c64f756a8ef529e7716
                )

            [1] => Array
                (
                    [source] => images/structure/glider-large.png
                    [target] => media/plg_system_cgwebp/_cache/images/structure/glider-large.webp?ver=e48d04766b597c64f756a8ef529e7716
                )

            [2] => Array
                (
                    [source] => images/banniere/phpsecinfo.png
                    [target] => media/plg_system_cgwebp/_cache/images/banniere/phpsecinfo.webp?ver=977ff7152175ac8b2ef70aee2c32bc30
                )

        )

)`
```

**Comment by conseilgouz** [comment]
Bonjour,

- Erreur HTTP_ACCEPT : quel type d'explorateur utilisez-vous ? j'ai testé avec edge/chrome/firefox et ils retournent bien HTTP_ACCEPT. Je vais modifier pour vérifier la présence de HTTP_ACCEPT, mais, si absent, je ne pourrai pas déterminer si Webp est actif sur votre explorateur.
- affichage en double : le plugin récupère toutes les images de la page et, s'elles n'ont pas encore  été converties, il les convertit en webp. Le tableau PHP contient la liste de toutes les images de la page, converties ou non. Je vais ajouté une information sur le tableau afin de différencier celles déjà converties des autres.

Concernant les erreurs que j'ai eu sur le template, j'ai testé avec fedaro_free_j5_2.2.2 à partir de https://warptheme.com/joomla-templates/fedaro/ et **je n'utilise pas le plugin de compatibilité Joomla.** Dans ce cas, j'ai une erreur en ligne 74 de templates\fedaro_free\html\com_content\article\default.php : ContentHelperRoute non trouvé et la même erreur sur le layout templates\fedaro_free\html\layouts\joomla\content\blog_style_default_related_item_title.php en ligne 28.

Pascal

**Comment by conseilgouz** [comment]
Je viens de mettre en ligne la version 1.2.5 du plugin qui corrige l'erreur HTTP_ACCEPT et ajoute une ligne [new] dans le tableau si le debug est activé.

Merci de me dire si cela répond à vos questions/problèmes.

Pascal

**Comment by ZerooCool** [comment]
Bonjour,

1- Pouvez vous remplacer " Répertoire * " par " Le répertoire de vos images * ".

2- Afficher par défaut dans le champ INPUT la valeur " images/ " comme exemple par défaut ?

3- Pouvez vous préciser dans la description, qu'il faut choisir entre les boutons "Même" ou "Media" ?

4- Pouvez vous préciser dans la description que par défaut, sur joomla, le répertoire des images a utiliser est "images/", pour traiter tout le répertoire images/ par défaut, mais, qu'il est possible d'exclure des répertoire d'images, et, des liens de menu ?

<hr>

Le plugin CG WebP optimise le chargement de vos pages en affichant des images WebP à la place de vos images jpg/png.
Quand une page est affichée, toutes les images jpg/png sont convertis en WEBP et stockées soit dans le même répertoire que l'image original **(Utiliser le bouton Même)**, soit dans le répertoire media/plg_system_cgwebp/_cache **(Utiliser le bouton Media)**.

L'utilisation du répertoire media **(media/plg_system_cgwebp/_cache)** est recommandée  **POUR STOCKER LES IMAGES GENEREES EN WEBP (Utiliser le bouton Media)**, les images WebP générées devenant faciles à retrouver.

Important : si l'option media est utilisée, les images webp générées par ce plugin seront supprimées lors de la désintallation du plugin.

**Comment by ZerooCool** [comment]
Préciser, il faut supprimer les images depuis le plugin, pour voir apparaitre les true false.
Cela fonctionne pour la première consultation de la page.
Une seconde consultation renvera false pour tout, les images étant déjà générées.

NB : J'ai un problème de configuration de cache avec mon virtualhost, supprimer les images et actualiser la page renvera toujours false. J'ai du changer de navigateur ( ou fermer le navigateur actuel pour le réouvrir le navigateur ce qui vide les cookies et fichiers de sites. )

Pour la première navigation, c'est OK. Si plusieurs fois la même image, la première va renvoyer true généré, et les autres false existe déjà.

La seconde navigation renvera TOUJOURS False, toutes les images étant déjà créées.
Cela peut poser un problème de compréhension, en cas de problème de cache ?
Si une erreur empêche de générer l'image, le message renvoyé sera également false ?

Pouvez vous préciser les 3 lignes du mode debug dans la description ?
target : source d'origine
A quoi correspond le hash utilisé derrière l'image ? Un rapport avec les règles  de [sécurité CSP, SRI hash](https://wiki.amis-sh.fr/index.php?title=Les_modules_de_Apache2#S%C3%A9curiser_les_styles_et_les_scripts_de_son_site_avec_CSP_SRI) ?
Valeur true / false, l'image a été générée / **L'image existe déjà, OU, n'a pas été générée ?**
```
Array
(
    [images/] => Array
        (
            [0] => Array
                (
                    [source] => images/structure/glider-large.png
                    [target] => media/plg_system_cgwebp/_cache/images/structure/glider-large.webp?ver=e48d04766b597c64f756a8ef529e7716
                    [new] => true
                )

            [1] => Array
                (
                    [source] => images/structure/glider-large.png
                    [target] => media/plg_system_cgwebp/_cache/images/structure/glider-large.webp?ver=e48d04766b597c64f756a8ef529e7716
                    [new] => false
                )

            [2] => Array
                (
                    [source] => images/banniere/phpsecinfo.png
                    [target] => media/plg_system_cgwebp/_cache/images/banniere/phpsecinfo.webp?ver=977ff7152175ac8b2ef70aee2c32bc30
                    [new] => true
                )

        )

)```

**Comment by ZerooCool** [comment]
Je n'ai plus d'erreur HTTP_ACCEPT dans les logs.

J'ai une seule erreur actuellement, concernant : 
```
[proxy_fcgi:error] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "VERSION" in /libraries/src/Updater/Adapter/ExtensionAdapter.php on line 113', referer: https://joomla.amis-sh.fr/
```

Je n'ai pas constaté les erreurs suivantes : 
> Concernant les erreurs que j'ai eu sur le template, j'ai testé avec fedaro_free_j5_2.2.2 à partir de https://warptheme.com/joomla-templates/fedaro/ et je n'utilise pas le plugin de compatibilité Joomla. Dans ce cas, j'ai une erreur en ligne 74 de templates\fedaro_free\html\com_content\article\default.php : ContentHelperRoute non trouvé et la même erreur sur le layout templates\fedaro_free\html\layouts\joomla\content\blog_style_default_related_item_title.php en ligne 28.


J'utilise PHP 8.2 avec la version 5.1.2 de joomla, Helix 2.1.1 et 2.2.1 pour le template considéré comme à jour.
Je n'ai pas d'informations concernant une mise à jour automatique vers la version 2.2.2.

**Comment by conseilgouz** [comment]
Bonjour,

Le hash ajouté à l'image permet de vérifier si l'image a été modifiée depuis sa génération au format webp et d'éviter de la recréer. Il permet aussi d'utiliser l'image du cache de l'explorateur si elle n'a pas évolué depuis son dernier affichage.

Je vais ajouter 'error' à la ligne [new] pour signaler les erreurs de conversion.
 
Je modifie la description des zones pour essayer de clarifier leur utilisation.

Concernant l'erreur proxy, je ne parviens pas à la reproduire.

Pascal

**Comment by ZerooCool** [comment]
Bonjour,
Pour l'erreur proxy, je suppose que c'est un problème de configuration Virtualhost pour le Referrer avec une url non transmise en variable : 
- Utilisation de php fpm ( [proxy_fcgi:error] )
- Referrer-Policy 'strict-origin' (Header) --> strict-origin-when-cross-origin
- Sinon, un problème de code "Undefined array key "VERSION" in /libraries/src/Updater/Adapter/ExtensionAdapter.php on line 113"

**Comment by conseilgouz** [comment]
la version 1.2.6, publiée plus tôt cette semaine, ajoute des descriptions aux paramètres du plugin.

**Comment by ZerooCool** [comment]
Merci.
J'ai installé la dernière version.
C'est parfait.
